import Foundation

/// One entry in the built-in catalogue.
///
/// `slug` is the stable identifier the seeder upserts on. It must never change for a
/// given movement — logged history is matched through it.
nonisolated struct SeedExercise: Sendable {
    let slug: String
    let name: String
    let primary: MuscleGroup
    let secondary: [MuscleGroup]
    let equipment: Equipment
    let mechanic: Mechanic
    let mode: TrackingMode
    let rest: Int

    init(
        slug: String,
        name: String,
        primary: MuscleGroup,
        secondary: [MuscleGroup] = [],
        equipment: Equipment,
        mechanic: Mechanic = .compound,
        mode: TrackingMode = .weightAndReps,
        rest: Int = 120
    ) {
        self.slug = slug
        self.name = name
        self.primary = primary
        self.secondary = secondary
        self.equipment = equipment
        self.mechanic = mechanic
        self.mode = mode
        self.rest = rest
    }
}

/// The built-in movement catalogue.
///
/// Bump `version` when entries are added or corrected; the seeder upserts by slug, so a
/// higher version grows the catalogue without duplicating rows or discarding the user's
/// favourites, notes and custom exercises.
nonisolated enum ExerciseCatalogue {
    static let version = 1

    /// Split into per-region arrays rather than one literal: a single 170-element array
    /// literal is pathological for the type checker.
    static var all: [SeedExercise] {
        chest + back + shoulders + arms + legs + core
    }

    // MARK: Chest

    static let chest: [SeedExercise] = [
        SeedExercise(slug: "barbell-bench-press", name: "Bench Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .barbell, rest: 180),
        SeedExercise(slug: "incline-barbell-bench-press", name: "Incline Bench Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .barbell, rest: 180),
        SeedExercise(slug: "decline-barbell-bench-press", name: "Decline Bench Press", primary: .chest,
                     secondary: [.triceps], equipment: .barbell, rest: 150),
        SeedExercise(slug: "dumbbell-bench-press", name: "Dumbbell Bench Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .dumbbell, rest: 150),
        SeedExercise(slug: "incline-dumbbell-bench-press", name: "Incline Dumbbell Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .dumbbell, rest: 150),
        SeedExercise(slug: "decline-dumbbell-press", name: "Decline Dumbbell Press", primary: .chest,
                     secondary: [.triceps], equipment: .dumbbell, rest: 150),
        SeedExercise(slug: "smith-machine-bench-press", name: "Smith Machine Bench Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .smithMachine, rest: 150),
        SeedExercise(slug: "machine-chest-press", name: "Machine Chest Press", primary: .chest,
                     secondary: [.triceps], equipment: .machine, rest: 120),
        SeedExercise(slug: "incline-machine-press", name: "Incline Machine Press", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .machine, rest: 120),
        SeedExercise(slug: "dumbbell-fly", name: "Dumbbell Fly", primary: .chest,
                     equipment: .dumbbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "incline-dumbbell-fly", name: "Incline Dumbbell Fly", primary: .chest,
                     equipment: .dumbbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "cable-fly", name: "Cable Fly", primary: .chest,
                     equipment: .cable, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "low-to-high-cable-fly", name: "Low-to-High Cable Fly", primary: .chest,
                     equipment: .cable, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "high-to-low-cable-fly", name: "High-to-Low Cable Fly", primary: .chest,
                     equipment: .cable, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "pec-deck", name: "Pec Deck", primary: .chest,
                     equipment: .machine, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "push-up", name: "Push-Up", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .bodyweight,
                     mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "incline-push-up", name: "Incline Push-Up", primary: .chest,
                     secondary: [.triceps], equipment: .bodyweight, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "decline-push-up", name: "Decline Push-Up", primary: .chest,
                     secondary: [.anteriorDeltoid, .triceps], equipment: .bodyweight,
                     mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "chest-dip", name: "Chest Dip", primary: .chest,
                     secondary: [.triceps, .anteriorDeltoid], equipment: .bodyweight,
                     mode: .bodyweightPlusAdded, rest: 150),
        SeedExercise(slug: "svend-press", name: "Svend Press", primary: .chest,
                     equipment: .other, mechanic: .isolation, rest: 60),
    ]

    // MARK: Back

    static let back: [SeedExercise] = [
        SeedExercise(slug: "deadlift", name: "Deadlift", primary: .lowerBack,
                     secondary: [.glutes, .hamstrings, .lats, .trapezius, .forearms],
                     equipment: .barbell, rest: 240),
        SeedExercise(slug: "sumo-deadlift", name: "Sumo Deadlift", primary: .lowerBack,
                     secondary: [.glutes, .quadriceps, .adductors, .trapezius],
                     equipment: .barbell, rest: 240),
        SeedExercise(slug: "trap-bar-deadlift", name: "Trap Bar Deadlift", primary: .lowerBack,
                     secondary: [.glutes, .quadriceps, .trapezius], equipment: .trapBar, rest: 210),
        SeedExercise(slug: "rack-pull", name: "Rack Pull", primary: .lowerBack,
                     secondary: [.trapezius, .lats, .forearms], equipment: .barbell, rest: 210),
        SeedExercise(slug: "pull-up", name: "Pull-Up", primary: .lats,
                     secondary: [.biceps, .rhomboids], equipment: .bodyweight,
                     mode: .bodyweightReps, rest: 150),
        SeedExercise(slug: "chin-up", name: "Chin-Up", primary: .lats,
                     secondary: [.biceps], equipment: .bodyweight, mode: .bodyweightReps, rest: 150),
        SeedExercise(slug: "weighted-pull-up", name: "Weighted Pull-Up", primary: .lats,
                     secondary: [.biceps, .rhomboids], equipment: .bodyweight,
                     mode: .bodyweightPlusAdded, rest: 180),
        SeedExercise(slug: "lat-pulldown", name: "Lat Pulldown", primary: .lats,
                     secondary: [.biceps, .rhomboids], equipment: .cable, rest: 120),
        SeedExercise(slug: "wide-grip-lat-pulldown", name: "Wide-Grip Lat Pulldown", primary: .lats,
                     secondary: [.rhomboids], equipment: .cable, rest: 120),
        SeedExercise(slug: "close-grip-lat-pulldown", name: "Close-Grip Lat Pulldown", primary: .lats,
                     secondary: [.biceps], equipment: .cable, rest: 120),
        SeedExercise(slug: "single-arm-lat-pulldown", name: "Single-Arm Lat Pulldown", primary: .lats,
                     secondary: [.biceps], equipment: .cable, rest: 90),
        SeedExercise(slug: "straight-arm-pulldown", name: "Straight-Arm Pulldown", primary: .lats,
                     equipment: .cable, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "barbell-row", name: "Barbell Row", primary: .lats,
                     secondary: [.rhomboids, .posteriorDeltoid, .biceps], equipment: .barbell, rest: 150),
        SeedExercise(slug: "pendlay-row", name: "Pendlay Row", primary: .lats,
                     secondary: [.rhomboids, .trapezius], equipment: .barbell, rest: 150),
        SeedExercise(slug: "dumbbell-row", name: "Dumbbell Row", primary: .lats,
                     secondary: [.rhomboids, .biceps], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "chest-supported-row", name: "Chest-Supported Row", primary: .rhomboids,
                     secondary: [.lats, .posteriorDeltoid], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "t-bar-row", name: "T-Bar Row", primary: .lats,
                     secondary: [.rhomboids, .trapezius], equipment: .barbell, rest: 150),
        SeedExercise(slug: "meadows-row", name: "Meadows Row", primary: .lats,
                     secondary: [.rhomboids, .posteriorDeltoid], equipment: .barbell, rest: 120),
        SeedExercise(slug: "seated-cable-row", name: "Seated Cable Row", primary: .rhomboids,
                     secondary: [.lats, .biceps], equipment: .cable, rest: 120),
        SeedExercise(slug: "wide-grip-seated-row", name: "Wide-Grip Seated Row", primary: .rhomboids,
                     secondary: [.posteriorDeltoid], equipment: .cable, rest: 120),
        SeedExercise(slug: "machine-row", name: "Machine Row", primary: .rhomboids,
                     secondary: [.lats, .biceps], equipment: .machine, rest: 120),
        SeedExercise(slug: "inverted-row", name: "Inverted Row", primary: .rhomboids,
                     secondary: [.lats, .biceps], equipment: .bodyweight, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "barbell-shrug", name: "Barbell Shrug", primary: .trapezius,
                     secondary: [.forearms], equipment: .barbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "dumbbell-shrug", name: "Dumbbell Shrug", primary: .trapezius,
                     secondary: [.forearms], equipment: .dumbbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "face-pull", name: "Face Pull", primary: .posteriorDeltoid,
                     secondary: [.rhomboids, .trapezius], equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "good-morning", name: "Good Morning", primary: .lowerBack,
                     secondary: [.hamstrings, .glutes], equipment: .barbell, rest: 150),
        SeedExercise(slug: "back-extension", name: "Back Extension", primary: .lowerBack,
                     secondary: [.glutes, .hamstrings], equipment: .bodyweight,
                     mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "reverse-hyperextension", name: "Reverse Hyperextension", primary: .lowerBack,
                     secondary: [.glutes], equipment: .machine, rest: 90),
    ]

    // MARK: Shoulders

    static let shoulders: [SeedExercise] = [
        SeedExercise(slug: "overhead-press", name: "Overhead Press", primary: .anteriorDeltoid,
                     secondary: [.lateralDeltoid, .triceps, .trapezius], equipment: .barbell, rest: 180),
        SeedExercise(slug: "push-press", name: "Push Press", primary: .anteriorDeltoid,
                     secondary: [.triceps, .quadriceps], equipment: .barbell, rest: 180),
        SeedExercise(slug: "seated-dumbbell-shoulder-press", name: "Seated Dumbbell Press",
                     primary: .anteriorDeltoid, secondary: [.lateralDeltoid, .triceps],
                     equipment: .dumbbell, rest: 150),
        SeedExercise(slug: "arnold-press", name: "Arnold Press", primary: .anteriorDeltoid,
                     secondary: [.lateralDeltoid, .triceps], equipment: .dumbbell, rest: 150),
        SeedExercise(slug: "machine-shoulder-press", name: "Machine Shoulder Press",
                     primary: .anteriorDeltoid, secondary: [.triceps], equipment: .machine, rest: 120),
        SeedExercise(slug: "smith-machine-overhead-press", name: "Smith Machine Overhead Press",
                     primary: .anteriorDeltoid, secondary: [.triceps], equipment: .smithMachine, rest: 150),
        SeedExercise(slug: "lateral-raise", name: "Lateral Raise", primary: .lateralDeltoid,
                     equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "cable-lateral-raise", name: "Cable Lateral Raise", primary: .lateralDeltoid,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "machine-lateral-raise", name: "Machine Lateral Raise", primary: .lateralDeltoid,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "leaning-lateral-raise", name: "Leaning Lateral Raise", primary: .lateralDeltoid,
                     equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "front-raise", name: "Front Raise", primary: .anteriorDeltoid,
                     equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "cable-front-raise", name: "Cable Front Raise", primary: .anteriorDeltoid,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "plate-front-raise", name: "Plate Front Raise", primary: .anteriorDeltoid,
                     equipment: .other, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "rear-delt-fly", name: "Rear Delt Fly", primary: .posteriorDeltoid,
                     secondary: [.rhomboids], equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "cable-rear-delt-fly", name: "Cable Rear Delt Fly", primary: .posteriorDeltoid,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "reverse-pec-deck", name: "Reverse Pec Deck", primary: .posteriorDeltoid,
                     secondary: [.rhomboids], equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "upright-row", name: "Upright Row", primary: .lateralDeltoid,
                     secondary: [.trapezius, .biceps], equipment: .barbell, rest: 90),
        SeedExercise(slug: "handstand-push-up", name: "Handstand Push-Up", primary: .anteriorDeltoid,
                     secondary: [.triceps, .trapezius], equipment: .bodyweight,
                     mode: .bodyweightReps, rest: 150),
    ]

    // MARK: Arms

    static let arms: [SeedExercise] = [
        // Biceps
        SeedExercise(slug: "barbell-curl", name: "Barbell Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .barbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "ez-bar-curl", name: "EZ Bar Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .ezBar, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "dumbbell-curl", name: "Dumbbell Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "alternating-dumbbell-curl", name: "Alternating Dumbbell Curl",
                     primary: .biceps, secondary: [.forearms], equipment: .dumbbell,
                     mechanic: .isolation, rest: 75),
        SeedExercise(slug: "hammer-curl", name: "Hammer Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "incline-dumbbell-curl", name: "Incline Dumbbell Curl", primary: .biceps,
                     equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "preacher-curl", name: "Preacher Curl", primary: .biceps,
                     equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "ez-bar-preacher-curl", name: "EZ Bar Preacher Curl", primary: .biceps,
                     equipment: .ezBar, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "concentration-curl", name: "Concentration Curl", primary: .biceps,
                     equipment: .dumbbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "cable-curl", name: "Cable Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "rope-hammer-curl", name: "Rope Hammer Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "spider-curl", name: "Spider Curl", primary: .biceps,
                     equipment: .dumbbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "machine-curl", name: "Machine Curl", primary: .biceps,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "zottman-curl", name: "Zottman Curl", primary: .biceps,
                     secondary: [.forearms], equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "drag-curl", name: "Drag Curl", primary: .biceps,
                     equipment: .barbell, mechanic: .isolation, rest: 75),
        // Triceps
        SeedExercise(slug: "close-grip-bench-press", name: "Close-Grip Bench Press", primary: .triceps,
                     secondary: [.chest, .anteriorDeltoid], equipment: .barbell, rest: 150),
        SeedExercise(slug: "jm-press", name: "JM Press", primary: .triceps,
                     secondary: [.chest], equipment: .barbell, rest: 120),
        SeedExercise(slug: "triceps-pushdown", name: "Triceps Pushdown", primary: .triceps,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "rope-pushdown", name: "Rope Pushdown", primary: .triceps,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "overhead-cable-extension", name: "Overhead Cable Extension", primary: .triceps,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "skull-crusher", name: "Skull Crusher", primary: .triceps,
                     equipment: .barbell, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "ez-bar-skull-crusher", name: "EZ Bar Skull Crusher", primary: .triceps,
                     equipment: .ezBar, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "dumbbell-overhead-extension", name: "Dumbbell Overhead Extension",
                     primary: .triceps, equipment: .dumbbell, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "dumbbell-kickback", name: "Dumbbell Kickback", primary: .triceps,
                     equipment: .dumbbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "machine-triceps-extension", name: "Machine Triceps Extension",
                     primary: .triceps, equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "bench-dip", name: "Bench Dip", primary: .triceps,
                     secondary: [.anteriorDeltoid], equipment: .bodyweight, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "triceps-dip", name: "Triceps Dip", primary: .triceps,
                     secondary: [.chest, .anteriorDeltoid], equipment: .bodyweight,
                     mode: .bodyweightPlusAdded, rest: 150),
        SeedExercise(slug: "diamond-push-up", name: "Diamond Push-Up", primary: .triceps,
                     secondary: [.chest], equipment: .bodyweight, mode: .bodyweightReps, rest: 90),
        // Forearms
        SeedExercise(slug: "reverse-curl", name: "Reverse Curl", primary: .forearms,
                     secondary: [.biceps], equipment: .ezBar, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "wrist-curl", name: "Wrist Curl", primary: .forearms,
                     equipment: .barbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "reverse-wrist-curl", name: "Reverse Wrist Curl", primary: .forearms,
                     equipment: .barbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "farmers-carry", name: "Farmer's Carry", primary: .forearms,
                     secondary: [.trapezius, .obliques], equipment: .dumbbell, mode: .timed, rest: 120),
        SeedExercise(slug: "dead-hang", name: "Dead Hang", primary: .forearms,
                     secondary: [.lats], equipment: .bodyweight, mechanic: .isolation,
                     mode: .timed, rest: 90),
        SeedExercise(slug: "plate-pinch", name: "Plate Pinch", primary: .forearms,
                     equipment: .other, mechanic: .isolation, mode: .timed, rest: 60),
    ]

    // MARK: Legs

    static let legs: [SeedExercise] = [
        SeedExercise(slug: "back-squat", name: "Back Squat", primary: .quadriceps,
                     secondary: [.glutes, .adductors, .lowerBack], equipment: .barbell, rest: 240),
        SeedExercise(slug: "front-squat", name: "Front Squat", primary: .quadriceps,
                     secondary: [.glutes, .abs], equipment: .barbell, rest: 210),
        SeedExercise(slug: "box-squat", name: "Box Squat", primary: .quadriceps,
                     secondary: [.glutes, .hamstrings], equipment: .barbell, rest: 210),
        SeedExercise(slug: "pause-squat", name: "Pause Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .barbell, rest: 210),
        SeedExercise(slug: "smith-machine-squat", name: "Smith Machine Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .smithMachine, rest: 180),
        SeedExercise(slug: "hack-squat", name: "Hack Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .machine, rest: 180),
        SeedExercise(slug: "goblet-squat", name: "Goblet Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "leg-press", name: "Leg Press", primary: .quadriceps,
                     secondary: [.glutes, .hamstrings], equipment: .machine, rest: 180),
        SeedExercise(slug: "single-leg-press", name: "Single-Leg Press", primary: .quadriceps,
                     secondary: [.glutes], equipment: .machine, rest: 120),
        SeedExercise(slug: "bulgarian-split-squat", name: "Bulgarian Split Squat", primary: .quadriceps,
                     secondary: [.glutes, .adductors], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "split-squat", name: "Split Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "walking-lunge", name: "Walking Lunge", primary: .quadriceps,
                     secondary: [.glutes, .hamstrings], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "reverse-lunge", name: "Reverse Lunge", primary: .quadriceps,
                     secondary: [.glutes], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "forward-lunge", name: "Forward Lunge", primary: .quadriceps,
                     secondary: [.glutes], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "curtsy-lunge", name: "Curtsy Lunge", primary: .glutes,
                     secondary: [.quadriceps, .abductors], equipment: .dumbbell, rest: 90),
        SeedExercise(slug: "step-up", name: "Step-Up", primary: .quadriceps,
                     secondary: [.glutes], equipment: .dumbbell, rest: 90),
        SeedExercise(slug: "leg-extension", name: "Leg Extension", primary: .quadriceps,
                     equipment: .machine, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "sissy-squat", name: "Sissy Squat", primary: .quadriceps,
                     equipment: .bodyweight, mechanic: .isolation, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "pistol-squat", name: "Pistol Squat", primary: .quadriceps,
                     secondary: [.glutes], equipment: .bodyweight, mode: .bodyweightReps, rest: 120),
        SeedExercise(slug: "wall-sit", name: "Wall Sit", primary: .quadriceps,
                     equipment: .bodyweight, mechanic: .isolation, mode: .timed, rest: 90),
        SeedExercise(slug: "romanian-deadlift", name: "Romanian Deadlift", primary: .hamstrings,
                     secondary: [.glutes, .lowerBack], equipment: .barbell, rest: 180),
        SeedExercise(slug: "stiff-leg-deadlift", name: "Stiff-Leg Deadlift", primary: .hamstrings,
                     secondary: [.glutes, .lowerBack], equipment: .barbell, rest: 180),
        SeedExercise(slug: "dumbbell-romanian-deadlift", name: "Dumbbell Romanian Deadlift",
                     primary: .hamstrings, secondary: [.glutes], equipment: .dumbbell, rest: 120),
        SeedExercise(slug: "lying-leg-curl", name: "Lying Leg Curl", primary: .hamstrings,
                     equipment: .machine, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "seated-leg-curl", name: "Seated Leg Curl", primary: .hamstrings,
                     equipment: .machine, mechanic: .isolation, rest: 90),
        SeedExercise(slug: "standing-leg-curl", name: "Standing Leg Curl", primary: .hamstrings,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "nordic-curl", name: "Nordic Curl", primary: .hamstrings,
                     equipment: .bodyweight, mode: .bodyweightReps, rest: 120),
        SeedExercise(slug: "glute-ham-raise", name: "Glute-Ham Raise", primary: .hamstrings,
                     secondary: [.glutes], equipment: .bodyweight, mode: .bodyweightReps, rest: 120),
        SeedExercise(slug: "hip-thrust", name: "Hip Thrust", primary: .glutes,
                     secondary: [.hamstrings], equipment: .barbell, rest: 150),
        SeedExercise(slug: "barbell-glute-bridge", name: "Barbell Glute Bridge", primary: .glutes,
                     secondary: [.hamstrings], equipment: .barbell, rest: 120),
        SeedExercise(slug: "machine-hip-thrust", name: "Machine Hip Thrust", primary: .glutes,
                     secondary: [.hamstrings], equipment: .machine, rest: 120),
        SeedExercise(slug: "cable-pull-through", name: "Cable Pull-Through", primary: .glutes,
                     secondary: [.hamstrings], equipment: .cable, rest: 90),
        SeedExercise(slug: "cable-kickback", name: "Cable Kickback", primary: .glutes,
                     equipment: .cable, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "kettlebell-swing", name: "Kettlebell Swing", primary: .glutes,
                     secondary: [.hamstrings, .lowerBack], equipment: .kettlebell, rest: 90),
        SeedExercise(slug: "hip-abduction-machine", name: "Hip Abduction Machine", primary: .abductors,
                     secondary: [.glutes], equipment: .machine, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "hip-adduction-machine", name: "Hip Adduction Machine", primary: .adductors,
                     equipment: .machine, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "standing-calf-raise", name: "Standing Calf Raise", primary: .calves,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "seated-calf-raise", name: "Seated Calf Raise", primary: .calves,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "leg-press-calf-raise", name: "Leg Press Calf Raise", primary: .calves,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "donkey-calf-raise", name: "Donkey Calf Raise", primary: .calves,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "single-leg-calf-raise", name: "Single-Leg Calf Raise", primary: .calves,
                     equipment: .bodyweight, mechanic: .isolation, mode: .bodyweightReps, rest: 60),
    ]

    // MARK: Core and neck

    static let core: [SeedExercise] = [
        SeedExercise(slug: "plank", name: "Plank", primary: .abs,
                     secondary: [.obliques], equipment: .bodyweight, mode: .timed, rest: 60),
        SeedExercise(slug: "weighted-plank", name: "Weighted Plank", primary: .abs,
                     secondary: [.obliques], equipment: .bodyweight, mode: .timed, rest: 75),
        SeedExercise(slug: "side-plank", name: "Side Plank", primary: .obliques,
                     secondary: [.abs], equipment: .bodyweight, mode: .timed, rest: 60),
        SeedExercise(slug: "hollow-body-hold", name: "Hollow Body Hold", primary: .abs,
                     equipment: .bodyweight, mode: .timed, rest: 60),
        SeedExercise(slug: "hanging-leg-raise", name: "Hanging Leg Raise", primary: .abs,
                     secondary: [.forearms], equipment: .bodyweight, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "hanging-knee-raise", name: "Hanging Knee Raise", primary: .abs,
                     secondary: [.forearms], equipment: .bodyweight, mode: .bodyweightReps, rest: 75),
        SeedExercise(slug: "toes-to-bar", name: "Toes to Bar", primary: .abs,
                     secondary: [.lats, .forearms], equipment: .bodyweight, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "captains-chair-leg-raise", name: "Captain's Chair Leg Raise", primary: .abs,
                     equipment: .machine, mode: .bodyweightReps, rest: 75),
        SeedExercise(slug: "lying-leg-raise", name: "Lying Leg Raise", primary: .abs,
                     equipment: .bodyweight, mechanic: .isolation, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "reverse-crunch", name: "Reverse Crunch", primary: .abs,
                     equipment: .bodyweight, mechanic: .isolation, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "crunch", name: "Crunch", primary: .abs,
                     equipment: .bodyweight, mechanic: .isolation, mode: .bodyweightReps, rest: 45),
        SeedExercise(slug: "bicycle-crunch", name: "Bicycle Crunch", primary: .obliques,
                     secondary: [.abs], equipment: .bodyweight, mode: .bodyweightReps, rest: 45),
        SeedExercise(slug: "sit-up", name: "Sit-Up", primary: .abs,
                     equipment: .bodyweight, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "decline-sit-up", name: "Decline Sit-Up", primary: .abs,
                     equipment: .bodyweight, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "v-up", name: "V-Up", primary: .abs,
                     secondary: [.quadriceps], equipment: .bodyweight, mode: .bodyweightReps, rest: 60),
        SeedExercise(slug: "cable-crunch", name: "Cable Crunch", primary: .abs,
                     equipment: .cable, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "machine-crunch", name: "Machine Crunch", primary: .abs,
                     equipment: .machine, mechanic: .isolation, rest: 75),
        SeedExercise(slug: "ab-wheel-rollout", name: "Ab Wheel Rollout", primary: .abs,
                     secondary: [.lats], equipment: .other, mode: .bodyweightReps, rest: 90),
        SeedExercise(slug: "dragon-flag", name: "Dragon Flag", primary: .abs,
                     secondary: [.lowerBack], equipment: .bodyweight, mode: .bodyweightReps, rest: 120),
        SeedExercise(slug: "russian-twist", name: "Russian Twist", primary: .obliques,
                     secondary: [.abs], equipment: .other, mode: .repsOnly, rest: 60),
        SeedExercise(slug: "cable-woodchop", name: "Cable Woodchop", primary: .obliques,
                     secondary: [.abs], equipment: .cable, rest: 75),
        SeedExercise(slug: "pallof-press", name: "Pallof Press", primary: .obliques,
                     secondary: [.abs], equipment: .cable, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "landmine-twist", name: "Landmine Twist", primary: .obliques,
                     secondary: [.abs], equipment: .barbell, rest: 75),
        SeedExercise(slug: "side-bend", name: "Side Bend", primary: .obliques,
                     equipment: .dumbbell, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "dead-bug", name: "Dead Bug", primary: .abs,
                     equipment: .bodyweight, mechanic: .isolation, mode: .repsOnly, rest: 45),
        SeedExercise(slug: "mountain-climber", name: "Mountain Climber", primary: .abs,
                     secondary: [.obliques], equipment: .bodyweight, mode: .repsOnly, rest: 45),
        SeedExercise(slug: "neck-curl", name: "Neck Curl", primary: .neck,
                     equipment: .other, mechanic: .isolation, rest: 60),
        SeedExercise(slug: "neck-extension", name: "Neck Extension", primary: .neck,
                     equipment: .other, mechanic: .isolation, rest: 60),
    ]
}
